# Generated by Django 5.0.6 on 2024-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_stores_item1description_stores_item2description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='item1name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stores',
            name='item2name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stores',
            name='item3name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
